server.port=8081
spring.application.name=product-service

aws.dynamodb.endpoint=http://localhost:8000
aws.dynamodb.region=us-east-1
aws.dynamodb.access-key=local
aws.dynamodb.secret-key=local
aws.dynamodb.table-name=Products

