server.port=8083
spring.application.name=payment-service

aws.dynamodb.endpoint=http://localhost:8000
aws.dynamodb.region=us-east-1
aws.dynamodb.accessKey=local
aws.dynamodb.secretKey=local
aws.dynamodb.tableName=Payments

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true